--changeset LyeshaKorotkevich:1
DROP TABLE IF EXISTS houses;
CREATE TABLE IF NOT EXISTS houses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    area        VARCHAR(255)                            NOT NULL,
    country     VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    street      VARCHAR(255)                            NOT NULL,
    number      INTEGER                                 NOT NULL,
    create_date TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_houses PRIMARY KEY (id)
);

ALTER TABLE houses
    ADD CONSTRAINT uc_houses_uuid UNIQUE (uuid);

ALTER TABLE houses
    ADD CONSTRAINT uc_houses_area_country_city_street_number_created UNIQUE (area, country, city, street, number, create_date);