CREATE TABLE people
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID                                    NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    surname         VARCHAR(255)                            NOT NULL,
    sex             VARCHAR(255)                            NOT NULL,
    create_date     TIMESTAMP                               NOT NULL,
    update_date     TIMESTAMP                               NOT NULL,
    house_id        BIGINT,
    passport_series VARCHAR(255),
    passport_number VARCHAR(255),
    CONSTRAINT pk_people PRIMARY KEY (id)
);

ALTER TABLE people
    ADD CONSTRAINT uc_people_uuid UNIQUE (uuid);

ALTER TABLE people
    ADD CONSTRAINT uc_people_passportSeries_passportNumber UNIQUE (passport_series, passport_number);

ALTER TABLE people
    ADD CONSTRAINT FK_PEOPLE_ON_HOUSE FOREIGN KEY (house_id) REFERENCES houses (id);