spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5438/housesDB

  jpa:
    properties:
      hibernate:
        ddl: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true