spring:
  datasource:
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5438/housesDB

  hibernate:
    ddl: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true